version: '3.4'

services:
  postscommentsapi:
    container_name: api
    build:
      context: .
      dockerfile: PostsCommentsApi/Dockerfile
    depends_on:
      - cache
      - db
      - elasticsearch
      - identity
    environment:
      - RedisHost=cache:6379
      - ElasticSearchHost=http://elasticsearch:9200
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=30001
    ports:
      - "30000:80"
      - "30001:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    networks:
      - api-network

  identity:
    container_name: identity
    build:
      context: .
      dockerfile: Identity/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=5101
    ports:
      - "5100:80"
      - "5101:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    networks:
      - api-network

  cache:
    image: redis
    container_name: cache
    ports:
      - "5001:6379"
    networks:
      - api-network

  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: db
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    ports:
      - "5000:1433"
    networks:
      - api-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    container_name: elasticsearch
    ports:
    - "9200:9200"
    volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - api-network

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.1
    container_name: kibana
    ports:
    - "5601:5601"
    depends_on:
    - elasticsearch
    networks:
      - api-network
networks:
  api-network:
    driver: bridge

volumes:
    elasticsearch-data: